### ISSUE TITLE
TimeShift doesnt start - Mint Linux 18.2 Sonya

### ISSUE THREAD

**Issue by sammy2k8** [teejee2008/timeshift#318]
**Describe the bug**

**To Reproduce**
3. Error message

**Expected behavior**

**Screenshots**

**System:**
 - Linux Distribution Name and Version: [e.g. Ubuntu 16.04]
 - Desktop [e.g. MATE, XFCE]
 - Application Version [e.g. v18.8]

***This is a free application created in my spare time. Consider making a donation if you need support for an issue.***

[![](https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif)](https://www.paypal.com/cgi-bin/webscr?business=teejeetech@gmail.com&cmd=_xclick&currency_code=USD&item_name=Timeshift%20Donation)

**Comment by pyroxar** [comment]
Can you reproduce this bug on the Linux Mint 19.1? Maybe problem has been solved?

**Comment by Simonmicro** [comment]
Well, i could reproduce it on debian stretch. I guess it has something to do with my new RAID setup (level 5 on mdadm). Before that (I don't know for sure, because some time passed) the gui worked fine. Now I only get:
`user@hostname:~$ sudo timeshift-gtk

** (timeshift-gtk:2506): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-9nrGfP6rr0: Connection refused
[Warning] Deleted invalid lock
**
ERROR:arraylist.c:957:gee_array_list_real_get: assertion failed: (index < _size)
Aborted
user@hostname:~$ sudo timeshift-launcher

** (timeshift-gtk:2609): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-9nrGfP6rr0: Connection refused
[Warning] Deleted invalid lock
**
ERROR:arraylist.c:957:gee_array_list_real_get: assertion failed: (index < _size)
/usr/bin/timeshift-launcher: line 30:  2609 Aborted                 ${app_command}`

Any ideas?

**Comment by emirror-de** [comment]
Hi all,

I had the same error as described above and I can support Simonmicro with his statement that it must have something to do with RAID systems.
On my PC i have a mdadm RAID 1 and RAID 5 attached. When I plug them out, the GUI works as expected. If they are plugged in, the error occurs and the GUI won't start.

I am running Ubuntu 18.10, output of `dpkg -l | grep timeshift`:
`timeshift 18.9.1-0~201809051631~ubuntu18.10.1 amd64 System restore utility`

**Comment by cajunjoel** [comment]
I also have a mdadm RAID 5 and had this problem of TimeShift not starting, but I recently discovered that TimeShift _was_ working. I see now that I am on a later version, which I installed around Feb 13 of this year.

`dpkg -l | grep timeshift`
`ii  timeshift    19.01-0~201901201321~ubuntu18.04.1       amd64        System restore utility`

If it matters, I'm on Linux Mint 19.1 Cinnamon and I previously was on TimeShift 18.9.1. I wonder if those on Mint 18 can force an upgrade to TimeShift 19.1 and try it out?

**Comment by Simonmicro** [comment]
Hmm, the error still appears on my system - here is my dpkg output (I've downloaded the deb recently, so it should be the newest release):
`dpkg -l | grep timeshift`
`ii  timeshift                            19.01                             amd64        System restore utility`
Sorry,
Simonmicro

**Comment by roycordero** [comment]
could someone fix this isuue? 
tengo debian 10 buster con openmediavault y usaba timeshift sin problemas pero instale un raid 5 y ahora no quiere funcionar timeshift :(
